{"name": "test_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <test_01.TestCase object at 0x000001EA642C4E80>\n\n    def test_03(self):\n        print('---用例03---')\n>       assert 0\nE       assert 0\n\ntest_01.py:17: AssertionError"}, "attachments": [{"name": "stdout", "source": "e5e05e55-1140-4732-954c-8a7baf6dcfa2-attachment.txt", "type": "text/plain"}], "start": 1645150190314, "stop": 1645150190314, "uuid": "5a3d6c2f-6079-44c9-930a-bc6e3c797484", "historyId": "3c7cc6a836224e76576e1c8357e05e6a", "testCaseId": "de97ba16260a6dc8e49dba2e8af1c38f", "fullName": "test_01.TestCase#test_03", "labels": [{"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "SH-QA-PC0190"}, {"name": "thread", "value": "20108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}